programa: SumaUnoSem.o semaforo.o
	g++ -o programa SumaUnoSem.o semaforo.o
SumaUnoSem.o: SumaUnoSem.c semaforo.h
	g++ -c SumaUnoSem.c semaforo.h
semaforo.o: semaforo.c semaforo.h
	g++ -c semaforo.c semaforo.h
