programa: pruebaShM.o semaforo.o
	g++ -o programa pruebaShM.o semaforo.o
pruebaShM.o: pruebaShM.c semaforo.h
	g++ -c pruebaShM.c semaforo.h
semaforo.o: semaforo.c semaforo.h
	g++ -c semaforo.c semaforo.h
