programa: PiPorSeries.o semaforo.o
	g++ -o programa PiPorSeries.o semaforo.o
PiPorSeries.o: PiPorSeries.c semaforo.h
	g++ -c PiPorSeries.c semaforo.h
semaforo.o: semaforo.c semaforo.h
	g++ -c semaforo.c semaforo.h
