programa: PiporSeriesConMensajes.o Buzon.o
	g++ -o programa PiporSeriesConMensajes.o Buzon.o
PiporSeriesConMensajes.o: PiporSeriesConMensajes.c Buzon.h
	g++ -c PiporSeriesConMensajes.c Buzon.h
Buzon.o: Buzon.c Buzon.h
	g++ -c Buzon.c Buzon.h
